name = "MakiePublicationTheme"
uuid = "3fbbcf8b-4a17-4fd7-8dae-ebb2ecac0782"
authors = ["Kim Louisa Auth <auth@chalmers.se> and contributors"]
version = "1.0.0-DEV"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
julia = "1.6.7"
Makie = "0.19.9, 0.20, 0.21"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
