name = "MakiePublicationTheme"
uuid = "3fbbcf8b-4a17-4fd7-8dae-ebb2ecac0782"
authors = ["Kim Louisa Auth <auth@chalmers.se> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
